export default {
    tracks: {
      items: [
        {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify: "https://open.spotify.com/artist/2iDVt6mFbtbDEZG5ax0dTi"
                },
                href: "https://api.spotify.com/v1/artists/2iDVt6mFbtbDEZG5ax0dTi",
                id: "2iDVt6mFbtbDEZG5ax0dTi",
                name: "Tulus",
                type: "artist",
                uri: "spotify:artist:2iDVt6mFbtbDEZG5ax0dTi"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/3R4IAF9ApqYeUQrv1ddyoR"
            },
            href: "https://api.spotify.com/v1/albums/3R4IAF9ApqYeUQrv1ddyoR",
            id: "3R4IAF9ApqYeUQrv1ddyoR",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273b55d26c578e30129b0a7e86e",
                width: 640
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02b55d26c578e30129b0a7e86e",
                width: 300
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851b55d26c578e30129b0a7e86e",
                width: 64
              }
            ],
            name: "Manusia",
            release_date: "2022-03-03",
            release_date_precision: "day",
            total_tracks: 10,
            type: "album",
            uri: "spotify:album:3R4IAF9ApqYeUQrv1ddyoR"
          },
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/2iDVt6mFbtbDEZG5ax0dTi"
              },
              href: "https://api.spotify.com/v1/artists/2iDVt6mFbtbDEZG5ax0dTi",
              id: "2iDVt6mFbtbDEZG5ax0dTi",
              name: "Tulus",
              type: "artist",
              uri: "spotify:artist:2iDVt6mFbtbDEZG5ax0dTi"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          disc_number: 1,
          duration_ms: 242000,
          explicit: false,
          external_ids: {
            isrc: "FR2X42253130"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/2hHeGD57S0BcopfVcmehdl"
          },
          href: "https://api.spotify.com/v1/tracks/2hHeGD57S0BcopfVcmehdl",
          id: "2hHeGD57S0BcopfVcmehdl",
          is_local: false,
          name: "Hati-Hati di Jalan",
          popularity: 84,
          preview_url: "https://p.scdn.co/mp3-preview/c5e70e742b9f7c131676f6cfb9c69e5fc4a4f85b?cid=cea9bd089578437e953d6e05f99f6868",
          track_number: 8,
          type: "track",
          uri: "spotify:track:2hHeGD57S0BcopfVcmehdl"
        },
        {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify: "https://open.spotify.com/artist/2iDVt6mFbtbDEZG5ax0dTi"
                },
                href: "https://api.spotify.com/v1/artists/2iDVt6mFbtbDEZG5ax0dTi",
                id: "2iDVt6mFbtbDEZG5ax0dTi",
                name: "Tulus",
                type: "artist",
                uri: "spotify:artist:2iDVt6mFbtbDEZG5ax0dTi"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/3R4IAF9ApqYeUQrv1ddyoR"
            },
            href: "https://api.spotify.com/v1/albums/3R4IAF9ApqYeUQrv1ddyoR",
            id: "3R4IAF9ApqYeUQrv1ddyoR",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273b55d26c578e30129b0a7e86e",
                width: 640
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02b55d26c578e30129b0a7e86e",
                width: 300
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851b55d26c578e30129b0a7e86e",
                width: 64
              }
            ],
            name: "Manusia",
            release_date: "2022-03-03",
            release_date_precision: "day",
            total_tracks: 10,
            type: "album",
            uri: "spotify:album:3R4IAF9ApqYeUQrv1ddyoR"
          },
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/2iDVt6mFbtbDEZG5ax0dTi"
              },
              href: "https://api.spotify.com/v1/artists/2iDVt6mFbtbDEZG5ax0dTi",
              id: "2iDVt6mFbtbDEZG5ax0dTi",
              name: "Tulus",
              type: "artist",
              uri: "spotify:artist:2iDVt6mFbtbDEZG5ax0dTi"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          disc_number: 1,
          duration_ms: 240000,
          explicit: false,
          external_ids: {
            isrc: "FR2X42253131"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/2qgjqbi96IAOBzZFC6H57U"
          },
          href: "https://api.spotify.com/v1/tracks/2qgjqbi96IAOBzZFC6H57U",
          id: "2qgjqbi96IAOBzZFC6H57U",
          is_local: false,
          name: "Diri",
          popularity: 77,
          preview_url: "https://p.scdn.co/mp3-preview/a1a754f5a7785b718e500b16ce4f897bd5184ed2?cid=cea9bd089578437e953d6e05f99f6868",
          track_number: 9,
          type: "track",
          uri: "spotify:track:2qgjqbi96IAOBzZFC6H57U"
        },
        {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify: "https://open.spotify.com/artist/2iDVt6mFbtbDEZG5ax0dTi"
                },
                href: "https://api.spotify.com/v1/artists/2iDVt6mFbtbDEZG5ax0dTi",
                id: "2iDVt6mFbtbDEZG5ax0dTi",
                name: "Tulus",
                type: "artist",
                uri: "spotify:artist:2iDVt6mFbtbDEZG5ax0dTi"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/4szhn3xPmOJklFAcqNvTnQ"
            },
            href: "https://api.spotify.com/v1/albums/4szhn3xPmOJklFAcqNvTnQ",
            id: "4szhn3xPmOJklFAcqNvTnQ",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b27371c65edbeed32af70b900637",
                width: 640
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e0271c65edbeed32af70b900637",
                width: 300
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d0000485171c65edbeed32af70b900637",
                width: 64
              }
            ],
            name: "Monokrom",
            release_date: "2016-08-03",
            release_date_precision: "day",
            total_tracks: 10,
            type: "album",
            uri: "spotify:album:4szhn3xPmOJklFAcqNvTnQ"
          },
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/2iDVt6mFbtbDEZG5ax0dTi"
              },
              href: "https://api.spotify.com/v1/artists/2iDVt6mFbtbDEZG5ax0dTi",
              id: "2iDVt6mFbtbDEZG5ax0dTi",
              name: "Tulus",
              type: "artist",
              uri: "spotify:artist:2iDVt6mFbtbDEZG5ax0dTi"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          disc_number: 1,
          duration_ms: 214567,
          explicit: false,
          external_ids: {
            isrc: "FR59R1636575"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/4GfK1qOF3uBWidbPlTCQRL"
          },
          href: "https://api.spotify.com/v1/tracks/4GfK1qOF3uBWidbPlTCQRL",
          id: "4GfK1qOF3uBWidbPlTCQRL",
          is_local: false,
          name: "Monokrom",
          popularity: 75,
          preview_url: "https://p.scdn.co/mp3-preview/d659b7b417864badfb3d0f0081d2ce1565493f35?cid=cea9bd089578437e953d6e05f99f6868",
          track_number: 10,
          type: "track",
          uri: "spotify:track:4GfK1qOF3uBWidbPlTCQRL"
        },
        {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify: "https://open.spotify.com/artist/2iDVt6mFbtbDEZG5ax0dTi"
                },
                href: "https://api.spotify.com/v1/artists/2iDVt6mFbtbDEZG5ax0dTi",
                id: "2iDVt6mFbtbDEZG5ax0dTi",
                name: "Tulus",
                type: "artist",
                uri: "spotify:artist:2iDVt6mFbtbDEZG5ax0dTi"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/3R4IAF9ApqYeUQrv1ddyoR"
            },
            href: "https://api.spotify.com/v1/albums/3R4IAF9ApqYeUQrv1ddyoR",
            id: "3R4IAF9ApqYeUQrv1ddyoR",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273b55d26c578e30129b0a7e86e",
                width: 640
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02b55d26c578e30129b0a7e86e",
                width: 300
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851b55d26c578e30129b0a7e86e",
                width: 64
              }
            ],
            name: "Manusia",
            release_date: "2022-03-03",
            release_date_precision: "day",
            total_tracks: 10,
            type: "album",
            uri: "spotify:album:3R4IAF9ApqYeUQrv1ddyoR"
          },
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/2iDVt6mFbtbDEZG5ax0dTi"
              },
              href: "https://api.spotify.com/v1/artists/2iDVt6mFbtbDEZG5ax0dTi",
              id: "2iDVt6mFbtbDEZG5ax0dTi",
              name: "Tulus",
              type: "artist",
              uri: "spotify:artist:2iDVt6mFbtbDEZG5ax0dTi"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          disc_number: 1,
          duration_ms: 170000,
          explicit: false,
          external_ids: {
            isrc: "FR2X42253127"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/32Pdf9eyXDEMoClEJW6yYP"
          },
          href: "https://api.spotify.com/v1/tracks/32Pdf9eyXDEMoClEJW6yYP",
          id: "32Pdf9eyXDEMoClEJW6yYP",
          is_local: false,
          name: "Interaksi",
          popularity: 74,
          preview_url: "https://p.scdn.co/mp3-preview/f42a4192c0c77a519c72d14fb5d3fc35019b5a87?cid=cea9bd089578437e953d6e05f99f6868",
          track_number: 4,
          type: "track",
          uri: "spotify:track:32Pdf9eyXDEMoClEJW6yYP"
        },
        {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify: "https://open.spotify.com/artist/2iDVt6mFbtbDEZG5ax0dTi"
                },
                href: "https://api.spotify.com/v1/artists/2iDVt6mFbtbDEZG5ax0dTi",
                id: "2iDVt6mFbtbDEZG5ax0dTi",
                name: "Tulus",
                type: "artist",
                uri: "spotify:artist:2iDVt6mFbtbDEZG5ax0dTi"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/3R4IAF9ApqYeUQrv1ddyoR"
            },
            href: "https://api.spotify.com/v1/albums/3R4IAF9ApqYeUQrv1ddyoR",
            id: "3R4IAF9ApqYeUQrv1ddyoR",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273b55d26c578e30129b0a7e86e",
                width: 640
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02b55d26c578e30129b0a7e86e",
                width: 300
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851b55d26c578e30129b0a7e86e",
                width: 64
              }
            ],
            name: "Manusia",
            release_date: "2022-03-03",
            release_date_precision: "day",
            total_tracks: 10,
            type: "album",
            uri: "spotify:album:3R4IAF9ApqYeUQrv1ddyoR"
          },
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/2iDVt6mFbtbDEZG5ax0dTi"
              },
              href: "https://api.spotify.com/v1/artists/2iDVt6mFbtbDEZG5ax0dTi",
              id: "2iDVt6mFbtbDEZG5ax0dTi",
              name: "Tulus",
              type: "artist",
              uri: "spotify:artist:2iDVt6mFbtbDEZG5ax0dTi"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          disc_number: 1,
          duration_ms: 254600,
          explicit: false,
          external_ids: {
            isrc: "FR10S2294308"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/5TReP8XK4aTOe2m44ZjQqz"
          },
          href: "https://api.spotify.com/v1/tracks/5TReP8XK4aTOe2m44ZjQqz",
          id: "5TReP8XK4aTOe2m44ZjQqz",
          is_local: false,
          name: "Tujuh Belas",
          popularity: 70,
          preview_url: "https://p.scdn.co/mp3-preview/2ddb5fcd8c9eb3cc5655546cec5b2ce3af38da45?cid=cea9bd089578437e953d6e05f99f6868",
          track_number: 1,
          type: "track",
          uri: "spotify:track:5TReP8XK4aTOe2m44ZjQqz"
        },
      ],
    }
  }